
<img src="Images/NumPy_logo.png" width="400">

# Programming for Data Analysis Assignment

## numpy.random package
***

**Assignment objectives:**

1. Explain the overall purpose of the package.
2. Explain the use of the “Simple random data” and “Permutations” functions. 
3. Explain the use and purpose of at least five “Distributions” functions.
4. Explain the use of seeds in generating pseudorandom numbers.

## 1. NumPy and random number generators
***

NumPy, stands for Numerical Python "is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more." [numpy.org](https://numpy.org/devdocs/user/whatisnumpy.html)

NumPy was created in 2005 by Travis Oliphant who incorporating features of the Numarray into Numeric, with extensive modifications. NumPy is open-source software and has many contributors. [Wikipedia](https://en.wikipedia.org/wiki/NumPy)

**`numpy.random`** is a module within the NumPy package which is used to generate pseudo-random values and provides a range of tools to  manipulate them. This module is similar to the Python standard library random but it works with numpy arrays.  It allows to create arrays of random numbers from various probability distributions and also randomly sample from arrays or lists. This module is frequently used to fake or simulate data which is an important tool in data analysis, scientific research, machine learning and multiple other areas. The simulated data becomes very handy as it can be used to test methods before applying them to the real data.

Python's standard library random  only samples one value at a time while numpy.random can efficiently generate arrays of sample values from various probability distributions and provides additional probability distributions to use. Numpy's random module is much faster and more efficient than the standard Python’s random library particularly when working with lots of samples, however for other simpler purposes the random module can be sufficient and even more efficient.

As computers cannot generate truly random numbers - they need a set of instructions to produce an output, that means they are predictable and reproducible which is beneficial when creating and testing code. Therefore both of the random modules can only produce what is called  pseudorandom numbers that may appear random but they are not truly so.

“Random number generators have applications in gambling, statistical sampling, computer simulation, cryptography, completely randomized design, and other areas where producing an unpredictable result is desirable.” Monte Carlo simulation uses random numbers to simulate real world problems. They are often used to assess the risk of a given trading strategy for options or stocks. A Monte Carlo simulator allow to visualize most of the potential outcomes which gives a much better idea regarding the risk of a decision. They are also used in cryptography – so long as the seed is secret. Sender and receiver can generate the same set of numbers automatically to use as keys.

In Machine learning random sampling  is often used an actual datasets for testing and evaluation analytical methods and algorithms. “Machine learning is about learning some properties of a data set and then testing those properties against another data set. A common practice in machine learning is to evaluate an algorithm by splitting a data set into two. We call one of those sets the training set, on which we learn some properties; we call the other set the testing set, on which we test the learned properties.”  The machine learning algorithms in the scikit-learn package use numpy.random in the background. 
[scikit-learn](https://scikit-learn.org/stable/tutorial/basic/tutorial.html)

“Numpy’s random number routines produce pseudo random numbers using combinations of a BitGenerator to create sequences and a Generator to use those sequences to sample from different statistical distributions” [Random sampling]( https://numpy.org/doc/stable/reference/random/index.html)

Let's create an instance of a generator using `numpy.random` package. But before we proceed, we need to do all the necessary imports first:


In [1]:
# importing NumPy module
import numpy as np

# for data analysis
import pandas as pd

# importing matplotlib and seaborn for plotting and visualisations
import matplotlib.pyplot as plt
import seaborn as sns

# We can create a new constructor using the default_rng method to get a new instance of a random number generator.
rng = np.random.default_rng()
rng

Generator(PCG64) at 0x7FE31B6CA7C0

"PCG is a family of simple fast space-efficient statistically good algorithms for random number generation. Unlike many general-purpose RNGs, they are also hard to predict." [pcg-random.org](https://www.pcg-random.org/index.html)

## 2.1 Simple random data
***

There are four methods in Simple random data which we going to explore below: **random, integers, choice** and **bytes.**

It is very easy to create a random number(s) using `numpy.random`. As a first example, let's create 5 random float numbers between 0 and 1 by using the instance of a random number generator which we have created above.

<span style="color:Blue; font-weight:bold;">random</span>([size, dtype, out]) returns random floats in the half-open interval [0.0, 1.0).

In [2]:
# returns an array of 5 floats (if no parameters are specified, returns just one number).
rng.random(5)

array([0.75189053, 0.35010682, 0.44419532, 0.01782156, 0.14602349])

In [3]:
# returns an array of 2x3 floats
rng.random((2,3))

array([[0.73867583, 0.20802432, 0.53308877],
       [0.7472625 , 0.60501797, 0.35335901]])

In [4]:
# Three-by-two array of random numbers from [-3, 0):
3 * rng.random((3, 2)) - 3

array([[-2.23601812, -1.48839806],
       [-2.17581033, -1.45082315],
       [-1.00752565, -2.80833329]])

<span style="color:Blue; font-weight:bold;">integers</span>(low[, high, size, dtype, endpoint])) returns random integers from low (inclusive) to high (exclusive), or if endpoint=True, low (inclusive) to high (inclusive).

In [5]:
# returns an integer between 0-9
rng.integers(10)

1

In [6]:
# returns an array of 10 numbers between 5-8
rng.integers(5, 8, 10)

array([5, 5, 5, 7, 7, 5, 7, 5, 7, 6])

<span style="color:Blue; font-weight:bold;">bytes</span>(length) returns random bytes. The length of the string to be returned must be provided to the numpy.random.bytes function.

In [7]:
# returns 10 random bytes
rng.bytes(10)

b'C\xe3\x98\x9c\xd9\xc0V##\xf7'

<span style="color:Blue; font-weight:bold;">choice</span>(a[, size, replace, p, axis, shuffle]) gmenerates a random sample from a given array. 

In [8]:
# choose 5 numbers at random from the range 0-19
rng.choice(20, 5)

array([ 2,  8, 19,  7,  7])

We can use **choice()** methods with other data types, for example strings

In [9]:
# create a list of strings
colors = ["green", "red", "blue", "orange", "white"]

# choose 2 items from the list
rng.choice(colors, size=2)

array(['white', 'blue'], dtype='<U6')

We can 'weight' the probability for each item in the list. In the example below the 5th and and the 3d items in the list are respectivle 5 times and 2 times more likely to be returned than the others.

In [10]:
rng.choice(colors, p=[0.1, 0.2, 0.1, 0.1, 0.5], size=6)

array(['white', 'green', 'white', 'white', 'red', 'white'], dtype='<U6')

## 2.2 Permutations
***

There are three permutations methods in the numpy.random package.

- <span style="color:Blue; font-weight:bold;">shuffle</span>(x[, axis]) is used to modify an array or sequence in-place by shuffling its contents.
- <span style="color:Blue; font-weight:bold;">permutation</span>(x[, axis]) is used to randomly permute a sequence, or return a permuted range.
- <span style="color:Blue; font-weight:bold;">permuted</span>(x[, axis, out]) is used to randomly permute x along axis *axis*.

These methods can be used to (re)arrange series of numbers or to change the order of samples in a sequence. In machine learning these functions are often used to separate a dataset into training and test sets. Permutation method can be used to shuffled multi-dimensional arrays. When shuffling rows of data it is usually important to keep the contents of the row together while the order of the rows will be moved about.
The main difference between "permutation" and  "shuffle" is that first one creates a new array while the other one alters the original array.

To get a better understanding of how it works, let's look at some examples below:

In [11]:
# creating an array of numbers 0 to 10
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# 'shuffles' the array, the original array is now altered
rng.shuffle(arr1)
arr1

array([7, 1, 8, 3, 9, 2, 0, 4, 5, 6])

In [13]:
arr2 = np.arange(2,41,2).reshape(4,5)   ## create a 4 by 5 two-dimensional array
arr2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [14]:
# shuffles the 2D array within rows only
rng.shuffle(arr2, axis=1)
arr2

array([[ 4,  8,  6,  2, 10],
       [14, 18, 16, 12, 20],
       [24, 28, 26, 22, 30],
       [34, 38, 36, 32, 40]])

Now let's look at permutation method when used on the same arrays

In [15]:
# creating an array of numbers 0 to 10
arr3 = np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# random permutation
rng.permutation(arr3)

array([4, 5, 7, 0, 6, 1, 2, 8, 3, 9])

In [17]:
# the original array is intact
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr4 = np.arange(2,41,2).reshape(4,5)   ## create a 4 by 5 two-dimensional array
arr4

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [19]:
# permutates the 2D array - rows only
rng.permutation(arr4)

array([[ 2,  4,  6,  8, 10],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [12, 14, 16, 18, 20]])

In [20]:
# permutates 'colums' in the 2D array
rng.permutation(arr4, axis=1)

array([[ 8,  6, 10,  4,  2],
       [18, 16, 20, 14, 12],
       [28, 26, 30, 24, 22],
       [38, 36, 40, 34, 32]])

In [21]:
# just to confirm, the original array is intact
arr4

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

If we use **permuted** method on the same array, we can notice that each slice along the given axis is shuffled independently of the others.

In [22]:
#rng.permuted(arr4, axis=1)

We can also use permutation to create a random array from a range

In [23]:
# creates a permutation of the numbers 0-49
print(rng.permutation(50))

[38 14  0 23 22 25 21 24 35 13 40 17 49 37 48 36 11 41  3  1 30 29  2 44
 10  6 16 18 28 19 12 31  9 20  5 42 39 15 46  8 33 32  4 45 26 34  7 43
 27 47]


## 3. Probability distribution
***

A probability distribution is a statistical function that describes all the possible values and likelihoods that a random variable can take within a given range. There are many different patterns of probability and random numbers can be drawn from various probability distributions.

Probability distributions are of two types:
1. Discrete Probability Distribution
2. Continuous Probability Distribution or Probability Density Function

A discrete random variable is one where its set of possible values is a collection of isolated points on the number line - it has a finite set of specific outcomes, while a continuous random variable is one where its set of possible values is an entire interval on the number line. Discrete random variables almost always come from counting while continuous random variables mostly come from measurement.

Probability distributions are used widely in data analytics, statistical analysis and machine learning. They can be simulated based on their mathematical properties. Probability distributions are derived from variance or uncertainty and show which outcomes are more likely and which are less likely.

There is a very long list of various probability distribution which can be found on [Wikipedia](https://en.wikipedia.org/wiki/List_of_probability_distributions). In this project we going to have a look at a five of most commonly used ones as example. 

## 3.1 Normal (Gaussian) Distribution


[Normal distribution](https://www.britannica.com/topic/normal-distribution), also known as Gaussian Distribution represents the behavior of most situations in the universe. It is the most important probability distribution in statistics for independent, random variables.  It has a symmetric, bell shaped density curve which is described by its mean 𝝁 and standard deviation 𝝈. It represents things like IQ Scores, heartbeats, people's heights and weights, among others.

The [`numpy.random.normal(loc=0.0, scale=1.0, size=None)`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.normal.html#numpy.random.Generator.normal) function generates random number in a bell shaped curve centred around zero but spread out according to the scale parameter.

The following parameters are used in the function:
- <span style="color:Blue; font-weight:bold;">loc</span> argument is used to specify the mean or the centre of the distribution (peak of the bell curve)
- <span style="color:Blue; font-weight:bold;">scale</span> is used to specify the standard deviation of the distribution (distance from the mean)
- <span style="color:Blue; font-weight:bold;">size</span> is the number of random variables to sample (shape of the array)

britannica - https://www.britannica.com/topic/normal-distribution
Wiki - https://en.wikipedia.org/wiki/Normal_distribution
statisticsbyjim - https://statisticsbyjim.com/basics/normal-distribution/